#! /bin/csh -f
#
# BOX      = BOXLENGTH
# NPART    = NUMBER OF PARTICLES
# NSTEP    = NUMBER OF TIMESTEPS
# NINIT    = NUMBER OF INITIALIZATION STEPS
# TEMP     = TEMPERATURE
# TSTEP    = TIMESTEP FOR INTEGRATION

set BOX    = 14.0
set NPART  = 1200
set NSTEP  = 500
set NINIT  = 100
set NPRINT = 10
set TEMP   = 1.5
set TSTEP  = 0.0005

cat > fort.21 <<endofdata
$BOX $NPART $NSTEP $TEMP $TSTEP $NINIT $NPRINT
endofdata

mpirun -v -w -O -c2c -nger N /home/course/MOLSIM/md-mpi/Source/md_nve

rm fort.21

exit
