Ccccccccccccccccccccccccccccccccccccccccccccccccccc
C     Maxpart   = Maximum Number Of Particles     C
C     Maxlength = Maximum Length Of The Chain     C
C     Maxtrial  = Maximum Numberof Trial Dirs.    C
Ccccccccccccccccccccccccccccccccccccccccccccccccccc

      Integer Maxpart,Maxlength,Maxtrial

      Parameter (Maxpart   = 100)
      Parameter (Maxlength = 5)
      Parameter (Maxtrial  = 5)
