# Plots columns generated by mdlj.c
# Cameron F Abrams cfa22@drexel.edu

import numpy as np
import matplotlib.pyplot as plt
import argparse as ap

parser=ap.ArgumentParser()
parser.add_argument("-l",default="log",type=str,help="log file")
parser.add_argument("-d",default='2',type=str,help="comma-separated-list of data columns to plot vs time")
parser.add_argument("-ylabel",default='energy ($\epsilon$)',type=str,help="y-axis label")
parser.add_argument("-o",default='out.png',type=str,help="output file name")
parser.add_argument("-show-column-labels",default=True,type=bool,help="show column labels")
args=parser.parse_args()

col_labels=[]
with open(args.l) as f:
    for l in f:
        tok=l.split()
        if tok[0]=="#LABELS":
            col_labels=tok[1:]
if args.show_column_labels:
    for i,c in enumerate(col_labels):
        print(i,c)
dat=np.loadtxt(args.l)
cols=list(map(int,args.d.split(',')))
x=dat[:,1]
y=[]
plot_labels=[]
for c in cols:
    y.append(dat[:,c])
    if len(col_labels)>0:
        plot_labels.append(col_labels[c])
    else:
        plot_labels.append('')
fig,ax=plt.subplots(1,1,figsize=(6,4))

for yy,l in zip(y,plot_labels):
    ax.plot(x,yy,label=l)

if len(col_labels)>0:
    ax.set_xlabel(col_labels[1])
ax.set_ylabel(args.ylabel)
plt.legend()
plt.savefig(args.o,bbox_inches='tight')
